---

## Avoid Error: No PostgreSQL clusters exist; see "man pg_createcluster"
## http://askubuntu.com/questions/646350/locale-warning-from-perl-stops-postgres-configuring
## https://github.com/ansible/ansible/issues/10698
#- replace: dest=/etc/ssh/sshd_config regexp='^AcceptEnv LANG LC_*' replace='#AcceptEnv LANG LC_*' backup=yes
- name: collect environment
  command: env
  register: env
  changed_when: false
- debug: var=env

- name: apt | postgres mig dependencies install
  apt: name={{item}} state=present
  with_items: "{{ migpostgres_pkg }}"
  environment:
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  register: pgsqlinstall
#- debug: var=pgsqlinstall
#- debug: var=pgsqlinstall.results
#- debug: var=pgsqlinstall.results[0]
#- debug: var=pgsqlinstall.results[0].stdout_lines

- block:
    - name: create postgres base cluster
      command: "pg_createcluster {{ postgres_v }} main --start"
      become: postgres
      environment:
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: en_US.UTF-8
      when: "'No PostgreSQL clusters exist' in pgsqlinstall.results[0].stdout_lines"
  when: pgsqlinstall is defined and pgsqlinstall.results[0].stdout_lines is defined
#  when: pgsqlinstall is defined and pgsqlinstall.results[0].stdout_lines is defined and pgsqlinstall.results[0].stdout_lines.find('No PostgreSQL clusters exist') != -1

