# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "centos/7"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site-mig.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.sudo = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "mig-postgresserver" => ["vmig-postgres" ],
       }
    end

    config.vm.define "vmig-postgres" do |vmig-postgres|
        vmig-postgres.vm.hostname = "vmig-postgres"
    end

end

